# Generated by Django 6.0.1 on 2026-01-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reja',
            name='sarlavha',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='kurs',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='yosh',
            field=models.PositiveIntegerField(),
        ),
    ]
